name: Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [8.3, 7.4]

    name: PHP${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: pdo_sqlite

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress
          composer update --prefer-dist --no-progress --working-dir=demo/bridge/monolog

      - name: Execute Unit Tests
        run: vendor/bin/phpunit --testsuite=Browser
